### ISSUE TITLE
Outbound link tracking seems an inappropriate invasion of privacy

### ISSUE THREAD

**Issue by larrysalibra** [Ourinternet/website#1]
Outbound link tracking added in commit bf0abc3c1a645b743f1b21ec93177ecbef7865b2 seems not to be in line with the spirit of this document. Perhaps warning users that you are tracking their behavior would be appropriate?

**Comment by cpsimpson** [comment]
Thanks for the feedback.  I have reverted the changes to add outbound link tracking, until a privacy statement can be added warning users.

**Comment by larrysalibra** [comment]
Thanks @cpsimpson ! That's really awesome!
